version: '3'

services:
  nginx:
    container_name: nginx
    build: ./server_nginx
    ports: 
      - "80:80"
    depends_on: 
      - django
  mysql:
    image: mysql
    container_name: django-mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=django_db
  django:
    container_name: django-main
    build: ./ohto
    working_dir: /django_project
    command: >
      bash -c "python3 /django_project/manage.py makemigrations
      && python3 /django_project/manage.py migrate
      && gunicorn --bind 0:8000 ohto.wsgi:application"
    expose: 
      - "8000"
    depends_on: 
      - mysql
    links:
      - mysql:django-mysql
    