# Generated by Django 4.0 on 2022-10-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, related_name='songs_in_playlist', to='music_demo.Song'),
        ),
    ]
