# Generated by Django 4.0 on 2022-10-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_demo', '0002_alter_playlist_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayListAndSongJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.IntegerField(default=0)),
                ('song_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
    ]
