# Generated by Django 4.0 on 2022-10-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_demo', '0003_playlistandsongjoin_remove_playlist_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayListTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.IntegerField(default=0)),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.IntegerField(default=0)),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
    ]
