# Generated by Django 4.0 on 2022-11-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_demo', '0004_song_tags_alter_moodtag_tag_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tags',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
