# Generated by Django 4.0 on 2022-11-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_demo', '0009_alter_playlist_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover_img',
            field=models.ImageField(blank=True, default='../media/accounts/profile/2022/11/이미지_2022._9._17._오후_8.55.jpg', null=True, upload_to='playlists/cover_images/%Y/%m'),
        ),
    ]
