# Generated by Django 4.0 on 2022-11-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_demo', '0005_playlist_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='playlists/cover_images/%Y/%m'),
        ),
    ]
