# Generated by Django 4.0 on 2022-11-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_demo', '0007_alter_song_artist_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
