# Generated by Django 4.0 on 2022-11-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_demo', '0008_alter_playlist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='playlists/cover_images/%Y/%m'),
        ),
    ]
